### ISSUE TITLE
你好，为什么总有错误提示

### ISSUE THREAD

**Issue by 404gods** [2lifetop/LightHouse_Automatic_Shutdown#23]
按要求部署的，run LH.py里总有：{"errcode":300001,"errmsg":"token is not exist"}
请问这是哪里没设置好吗？
另外提个小建议，希望能有推送测试的功能，或查询即时流量的功能，谢谢

**Comment by 2lifetop** [comment]
LH.py里加了钉钉通知，不需要的话直接忽视即可，需要的话可以自己补充一下钉钉的机器人token即可
