### ISSUE TITLE
TG酱 token执行后提示这个错误

### ISSUE THREAD

**Issue by dand0285** [2lifetop/LightHouse_Automatic_Shutdown#24]
{"errcode":300001,"errmsg":"token is not exist"}

**Comment by CodeFishK** [comment]
同样的错误+1，已经加上双引号
![image](https://user-images.githubusercontent.com/38446347/140704486-170265ac-2b61-4d0e-bf66-23aab7b9240a.png)

**Comment by 2lifetop** [comment]
这个是钉钉的token没设置导致的，不用钉钉可以不用管
